name = "stats-for-startups"
compatibility_date = "2025-03-11"
compatibility_flags = ["nodejs_compat"]

# Configure build settings
[build]
command = "npm run build"

# Configure site settings
[site]
bucket = "out"
